[package]
name = "pomodoro"
version = "0.1.0"
authors = ["colton <cloftus@princeton.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
fstrings = "0.2.3"
libnotify = "1.0.3"
